import numpy as np
import pandas as pd
import scipy.stats as s
import itertools
#functions for calculating features for use in seizure detection algorithm

def allFeatures(data):
    output = []
    chans = len(data.ix[1,:])
    freq = np.fft.fftfreq(len(data['time']),1.0/len(data['time']))
    maxFreqs = []
    times = len(data.ix[:,1])-1 
    featureList = []
    delta1 = data.values[1:,:] - data.values[:times,:] # the 1st derivative
    glob1 = pd.DataFrame(delta1)
    freq1 = np.fft.fftfreq(len(glob1.ix[:,0]),1.0/len(glob1.ix[:,0]))
    maxFreqs1 = []
    delta2 = delta1[1:,:] - delta1[:times-1,:] # the 2nd derivative
    glob2 = pd.DataFrame(delta2)
    freq2 = np.fft.fftfreq(len(glob2.ix[:,0]),1.0/len(glob2.ix[:,0]))
    maxFreqs2 = []
# Channel Features
    for i in range(1,chans):
        output.append(data.ix[:,i].abs().max())
        featureList.append('chan%iMaxAmp'%(i-1))
        output.append(data.ix[:,i].abs().mean())
        featureList.append('chan%iMeanAmp'%(i-1))
        output.append(data.ix[:,i].abs().median())
        featureList.append('chan%iMedianAmp'%(i-1))
        output.append(data.ix[:,i].abs().var()) 
        featureList.append('chan%iVarAmp'%(i-1))
        output.append(abs(s.skew(np.abs(data.ix[:,i]))))
        featureList.append('chan%iSkewAmp'%(i-1)) 
        output.append(abs(s.kurtosis(np.abs(data.ix[:,i]))))
        featureList.append('chan%iKurtosisAmp'%(i-1)) 
        output.append(abs(np.fft.fft(data.ix[:,i])).max())
        featureList.append('chan%iMaxFourAmp'%(i-1))
        output.append(abs(np.fft.fft(data.ix[:,i])).mean())
        featureList.append('chan%iMeanFourAmp'%(i-1))
        output.append(abs(np.median(np.fft.fft(data.ix[:,i]))))
        featureList.append('chan%iMedianFourAmp'%(i-1))
        output.append(abs(np.fft.fft(data.ix[:,i])).var())
        featureList.append('chan%iVarFourAmp'%(i-1))
        output.append(abs(s.skew(abs(np.fft.fft(data.ix[:,i])))))
        featureList.append('chan%iSkewFourAmp'%(i-1))
        output.append(abs(s.kurtosis(abs(np.fft.fft(data.ix[:,i])))))
        featureList.append('chan%iKurtosisFourAmp'%(i-1))
        ft = abs(np.fft.fft(data.ix[:,i]))
        output.append(abs(freq[np.argmax(ft)]))
        featureList.append('chan%iMaxFreq'%(i-1))
# 1st Derivative Channel Features
        output.append(np.abs(delta1[:,i]).max())
        featureList.append('chan%iMaxAmpDel1'%(i-1))
        output.append(np.abs(delta1[:,i]).mean())
        featureList.append('chan%iMeanAmpDel1'%(i-1))
        output.append(np.median(np.abs(delta1[:,i])))
        featureList.append('chan%iMedianAmpDel1'%(i-1))
        output.append(np.abs(delta1[:,i]).var()) 
        featureList.append('chan%iVarAmpDel1'%(i-1))
        output.append(abs(s.skew(np.abs(delta1[:,i]))))
        featureList.append('chan%iSkewAmpDel1'%(i-1)) 
        output.append(abs(s.kurtosis(np.abs(delta1[:,i]))))
        featureList.append('chan%iKurtosisAmpDel1'%(i-1)) 
        output.append(abs(np.fft.fft(delta1[:,i])).max())
        featureList.append('chan%iMaxFourAmpDel1'%(i-1))
        output.append(abs(np.fft.fft(delta1[:,i])).mean())
        featureList.append('chan%iMeanFourAmpDel1'%(i-1))
        output.append(abs(np.median(np.fft.fft(delta1[:,i]))))
        featureList.append('chan%iMedianFourAmpDel1'%(i-1))
        output.append(abs(np.fft.fft(delta1[:,i])).var())
        featureList.append('chan%iVarFourAmpDel1'%(i-1))
        output.append(abs(s.skew(abs(np.fft.fft(delta1[:,i])))))
        featureList.append('chan%iSkewFourAmpDel1'%(i-1))
        output.append(abs(s.kurtosis(abs(np.fft.fft(delta1[:,i])))))
        featureList.append('chan%iKurtosisFourAmpDel1'%(i-1))
        ft = abs(np.fft.fft(delta1[:,i]))
        output.append(abs(freq1[np.argmax(ft)]))
        featureList.append('chan%iMaxFreqDel1'%(i-1))
# 2nd Derivative Channel Features
        output.append(np.abs(delta2[:,i]).max())
        featureList.append('chan%iMaxAmpDel2'%(i-1))
        output.append(np.abs(delta2[:,i]).mean())
        featureList.append('chan%iMeanAmpDel2'%(i-1))
        output.append(np.median(np.abs(delta2[:,i])))
        featureList.append('chan%iMedianAmpDel2'%(i-1))
        output.append(np.abs(delta2[:,i]).var()) 
        featureList.append('chan%iVarAmpDel2'%(i-1))
        output.append(abs(s.skew(np.abs(delta2[:,i]))))
        featureList.append('chan%iSkewAmpDel2'%(i-1)) 
        output.append(abs(s.kurtosis(np.abs(delta2[:,i]))))
        featureList.append('chan%iKurtosisAmpDel2'%(i-1)) 
        output.append(abs(np.fft.fft(delta2[:,i])).max())
        featureList.append('chan%iMaxFourAmpDel2'%(i-1))
        output.append(abs(np.fft.fft(delta2[:,i])).mean())
        featureList.append('chan%iMeanFourAmpDel2'%(i-1))
        output.append(abs(np.median(np.fft.fft(delta2[:,i]))))
        featureList.append('chan%iMedianFourAmpDel2'%(i-1))
        output.append(abs(np.fft.fft(delta2[:,i])).var())
        featureList.append('chan%iVarFourAmpDel2'%(i-1))
        output.append(abs(s.skew(abs(np.fft.fft(delta2[:,i])))))
        featureList.append('chan%iSkewFourAmpDel2'%(i-1))
        output.append(abs(s.kurtosis(abs(np.fft.fft(delta2[:,i])))))
        featureList.append('chan%iKurtosisFourAmpDel2'%(i-1))
        ft = abs(np.fft.fft(delta2[:,i]))
        output.append(abs(freq2[np.argmax(ft)]))
        featureList.append('chan%iMaxFreqDel2'%(i-1))
# Global Features
    output.append(data.ix[:,1:].abs().apply(np.max).max())
    featureList.append('maxAmp')
    output.append(data.ix[:,1:].abs().apply(np.max).mean())
    featureList.append('meanAmp')
    output.append(data.ix[:,1:].abs().apply(np.max).median())
    featureList.append('medianAmp')
    output.append(data.ix[:,1:].abs().apply(np.max).var())
    featureList.append('varAmp')
    output.append(np.array([abs(np.fft.fft(data['chan%i'%i])).max() for i in range(len(data.columns) - 1)]).max())
    featureList.append('maxFourAmp')
    output.append(np.array([abs(np.fft.fft(data['chan%i'%i])).max() for i in range(len(data.columns) - 1)]).mean())
    featureList.append('meanFourAmp')
    output.append(np.array([abs(np.fft.fft(data['chan%i'%i])).max() for i in range(len(data.columns) - 1)]).var())
    featureList.append('varFourAmp')
    for i in range(len(data.columns)-1):
        ft = abs(np.fft.fft(data['chan%i'%i]))
        maxFreqs.append(abs(freq[np.argmax(ft)]))
    output.append(np.max(maxFreqs))
    featureList.append('maxFreq')
    output.append(np.mean(maxFreqs))
    featureList.append('meanFreq')
    output.append(np.median(maxFreqs))
    featureList.append('medianFreq')
    output.append(np.var(maxFreqs))
    featureList.append('varFreq')
    combs = []
    [combs.append(a) for a in (itertools.combinations(list(data.columns)[1:], 2))] 
    covs = [np.cov(data.ix[:,combs[k][0]], data.ix[:,combs[k][1]])[0,1] for k in np.arange(0,len(combs)) ]
    output.append(np.mean(np.abs(covs)))
    featureList.append('coVar')
# 1st Derivative Global Features
    output.append(glob1.ix[:,1:].abs().apply(np.max).max())
    featureList.append('maxAmpDel1')
    output.append(glob1.ix[:,1:].abs().apply(np.max).mean())
    featureList.append('meanAmpDel1')
    output.append(glob1.ix[:,1:].abs().apply(np.max).median())
    featureList.append('medianAmpDel1')
    output.append(glob1.ix[:,1:].abs().apply(np.max).var())
    featureList.append('varAmpDel1')
    output.append(np.array([abs(np.fft.fft(glob1.ix[:,i])).max() for i in range(len(glob1.columns) - 1)]).max())
    featureList.append('maxFourAmpDel1')
    output.append(np.array([abs(np.fft.fft(glob1.ix[:,i])).max() for i in range(len(glob1.columns) - 1)]).mean())
    featureList.append('meanFourAmpDel1')
    output.append(np.array([abs(np.fft.fft(glob1.ix[:,i])).max() for i in range(len(glob1.columns) - 1)]).var())
    featureList.append('varFourAmpDel1')
    for i in range(len(glob1.columns)-1):
        ft = abs(np.fft.fft(glob1.ix[:,i]))
        maxFreqs1.append(abs(freq[np.argmax(ft)]))
    output.append(np.max(maxFreqs1))
    featureList.append('maxFreqDel1')
    output.append(np.mean(maxFreqs1))
    featureList.append('meanFreqDel1')
    output.append(np.median(maxFreqs1))
    featureList.append('medianFreqDel1')
    output.append(np.var(maxFreqs1))
    featureList.append('varFreqDel1')
    combs = []
    [combs.append(a) for a in (itertools.combinations(list(glob1.columns)[1:], 2))] 
    covs = [np.cov(glob1.ix[:,combs[k][0]], glob1.ix[:,combs[k][1]])[0,1] for k in np.arange(0,len(combs)) ]
    output.append(np.mean(np.abs(covs)))
    featureList.append('coVarDel1')
# 2nd Derivative Global Features
    output.append(glob2.ix[:,1:].abs().apply(np.max).max())
    featureList.append('maxAmpDel2')
    output.append(glob2.ix[:,1:].abs().apply(np.max).mean())
    featureList.append('meanAmpDel2')
    output.append(glob2.ix[:,1:].abs().apply(np.max).median())
    featureList.append('medianAmpDel2')
    output.append(glob2.ix[:,1:].abs().apply(np.max).var())
    featureList.append('varAmpDel2')
    output.append(np.array([abs(np.fft.fft(glob2.ix[:,i])).max() for i in range(len(glob2.columns) - 1)]).max())
    featureList.append('maxFourAmpDel2')
    output.append(np.array([abs(np.fft.fft(glob2.ix[:,i])).max() for i in range(len(glob2.columns) - 1)]).mean())
    featureList.append('meanFourAmpDel2')
    output.append(np.array([abs(np.fft.fft(glob2.ix[:,i])).max() for i in range(len(glob2.columns) - 1)]).var())
    featureList.append('varFourAmpDel2')
    for i in range(len(glob2.columns)-1):
        ft = abs(np.fft.fft(glob2.ix[:,i]))
        maxFreqs2.append(abs(freq[np.argmax(ft)]))
    output.append(np.max(maxFreqs2))
    featureList.append('maxFreqDel2')
    output.append(np.mean(maxFreqs2))
    featureList.append('meanFreqDel2')
    output.append(np.median(maxFreqs2))
    featureList.append('medianFreqDel2')
    output.append(np.var(maxFreqs2))
    featureList.append('varFreqDel2')
    combs = []
    [combs.append(a) for a in (itertools.combinations(list(glob2.columns)[1:], 2))] 
    covs = [np.cov(glob2.ix[:,combs[k][0]], glob2.ix[:,combs[k][1]])[0,1] for k in np.arange(0,len(combs)) ]
    output.append(np.mean(np.abs(covs)))
    featureList.append('coVarDel2')
    return pd.DataFrame({'allFeats':output},index=featureList).T


#Dictionary associates functions with string names so that features can be easily selected later
funcDict = {'allFeats'      : allFeatures}
